version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: dictionary
      MYSQL_ROOT_PASSWORD: default@2024
      MYSQL_PASSWORD: default@2024
      MYSQL_USER: laravel
    volumes:
      - ./database/mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app_network

  # PHP Laravel Application
  laravel_app:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./api:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app_network

  # React with Vite Application
  react_app:
    build:
      context: ./front
      dockerfile: Dockerfile.front
    container_name: react_app
    restart: unless-stopped
    ports:
      - "3000:5173"
    volumes:
      - ./front:/app
      - /app/node_modules
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

